server {
    listen 80;
    server_name kdt-pt-1-pj-2-team03.elicecoding.com;  
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}