server {
    listen 80;
    listen 443 ssl;
    server_name kdt-pt-1-pj-2-team03.elicecoding.com;

    ssl_certificate /etc/letsencrypt/live/kdt-pt-1-pj-2-team03.elicecoding.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kdt-pt-1-pj-2-team03.elicecoding.com/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name kdt-pt-1-pj-2-team03.elicecoding.com;
    return 301 https://$server_name$request_uri;
}